spring:
  application:
    name: "order-service"


server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
